export const RENTAL_CAR_STATUS_AVAILABLE = "AVAILABLE";
export const RENTAL_CAR_STATUS_BOOKED = "BOOKED";
export const RENTAL_CAR_STATUS_RENTED = "RENTED";
export const RENTAL_CAR_STATUS_UNAVAILABLE = "UNAVAILABLE";
