pages:
  stage: deploy
  script:
    - mkdir -p public
    - |
      for item in *; do
        if [ "$item" != "public" ]; then
          cp -r "$item" public/
        fi
      done
  artifacts:
    paths:
      - public
  only:
    - design
